dolittle/platform-api

pkg/platform/application/service.go, pkg/platform/doc.go, pkg/platform/microservice/service.go, pkg/platform/microservice/simple_repo.go, pkg/platform/storage/doc.go, pkg/platform/storage/git/application.go, pkg/platform/storage/git/git_storage.go, pkg/platform/storage/git/studio.go
- Lock down edit / delete to tenants which can.
- We now check the git repo for a studio.json file which will have studioconfig, to give us a chance to expose the site but also lock it down.
=> Making delete work

cmd/microservice/build-customers.go, cmd/microservice/git-test.go, cmd/microservice/root.go, cmd/microservice/server.go, cmd/microservice/update-repo.go, docs/microservice.md
Able to change which gitRepo to use.
https://app.asana.com/0/0/1200395926613616/f
=> Making gitRepo branch configruable

cmd/microservice/build-applications.go, cmd/microservice/build-customers.go, cmd/microservice/server.go, docs/api.md, docs/microservice.md, pkg/dolittle/k8s/networkpolicy.go, pkg/platform/application/service.go, pkg/platform/businessmoment/doc.go, pkg/platform/businessmoment/service.go, pkg/platform/doc.go, pkg/platform/k8s_repo.go, pkg/platform/microservice/businessmomentsadaptor/doc.go, pkg/platform/microservice/businessmomentsadaptor/k8s_businessmomentsadaptor.go, pkg/platform/microservice/businessmomentsadaptor_repo.go, pkg/platform/microservice/doc.go, pkg/platform/microservice/handle_businessmomentsadaptor.go, pkg/platform/microservice/service.go, pkg/platform/microservice/simple_repo.go, pkg/platform/storage/doc.go, pkg/platform/storage/git/businessmoment.go, pkg/platform/storage/git/microservice.go, pkg/platform/storage/git/studio.go
- Adding Networking Policy to Microservice
- Adding businessmoments configmap for use with businessmoments microservice
- Saving businessmoments moment from api to git and updating configmap for businessmoments microservice
- Saving businessmoments entities from api to git and updating configmap for businessmoments microservice
=> An api to save business moments to git

cmd/microservice/server.go, docs/api.md, go.mod, pkg/platform/doc.go, pkg/platform/k8s_repo.go, pkg/platform/microservice/service.go, pkg/utils/http.go
- configmap api to let the user download the configmap
- secret api to download secrets, currently only allowing "XXX-secret-env-variables".
https://app.asana.com/0/1200403658239260/1200315293318506/f
=> Config file endpoint

cmd/microservice/build-applications.go, cmd/microservice/build-terraform-info.go, cmd/microservice/git-test.go, cmd/microservice/root.go, cmd/microservice/server.go, cmd/microservice/share.go, cmd/microservice/update-repo.go, docs/devlopment-raw-data-log.md, pkg/platform/insights/service.go, pkg/platform/microservice/handle_businessmomentsadaptor.go, pkg/platform/microservice/handle_rawdatalogingestor.go, pkg/platform/microservice/service.go, pkg/platform/storage/doc.go, pkg/platform/storage/git/application.go, pkg/platform/storage/git/businessmoment.go, pkg/platform/storage/git/git_storage.go, pkg/platform/storage/git/microservice.go, pkg/platform/storage/git/studio.go, pkg/platform/storage/git/terraform.go
- Bringing GIT_REPO_XXX environment variables into play
Linked to https://app.asana.com/0/1200747172416688/1200440882894819/f
=> Removing hardcoded git variables

pkg/platform/microservice/purchaseorderapi/handler.go
Add handling of an error
- An error that was not handled
- Moved saving of purchase order api to git repo right after the microservice is created
=> Unhandled error

pkg/platform/doc.go, pkg/platform/microservice/handle_rawdatalogingestor.go, pkg/platform/microservice/purchaseorderapi/handler.go, pkg/platform/microservice/rawdatalog/repo.go, pkg/platform/microservice/rawdatalog/repo_test.go
Summary of the PR here. The GitHub release description is created from this comment so keep it nice and descriptive.
Remember to remove sections that you don't need or use.
- Describe the added features
- Describe the outwards facing code change
- Describe the fix and the bug
- Describe what was removed and why
- Describe the security issue and the fix
- Describe the part of the code being deprecated and why
=> Use ingress from Studio when creating PurchaseOrderAPI and RawDataLog

pkg/platform/microservice/purchaseorderapi/handler.go
Fixes some typos in the HTTP responses in PurchaseOrderAPI handler
- Typos in POAPI handler HTTP responses
=> Fixes typos in POAPI handler HTTP responses

cmd/microservice/build-terraform-info.go, pkg/platform/storage/git/terraform.go
Making build-terraform-info aware of the platform-environment
=> Building from terraform is now aware of the platform-environment

cmd/microservice/server.go, pkg/middleware/middleware.go
- Formatting server
- Bringing middleware.RestrictHandlerWithSharedSecret
Linked to #43
=> Server formatting

cmd/microservice/server.go, pkg/platform/cicd/service.go, pkg/platform/k8s_repo.go, pkg/platform/microservice/doc.go, pkg/platform/microservice/service.go
- Endpoint for service-account credentials
- Endpoint for container-registry credentials
=> Endpoints for some credentials

cmd/microservice/server.go, pkg/platform/application/service.go, pkg/platform/cicd/service.go, pkg/platform/k8s_repo.go, pkg/platform/microservice/service.go
- Specific endpoint for devops to not expose all service accounts.
- Lookup service account to find the secret name.
=> Not json + first need to lookup service account

pkg/dolittle/k8s/configmaps.go
- Adding management port to endpoints.json
=> Supporting 7.1.0 runtime in the platform

.gitignore, Makefile, pkg/platform/microservice/businessmomentsadaptor/suite_test.go, pkg/platform/microservice/parser/suite_test.go, pkg/platform/microservice/purchaseorderapi/suite_test.go, pkg/platform/microservice/rawdatalog/suite_test.go, pkg/platform/microservice/suite_test.go, pkg/platform/suite_test.go, pkg/platform/tenant/suite_test.go, pkg/rawdatalog/suite_test.go, pkg/utils/suite_test.go, scripts/total_coverage.sh
- Added a makefile to make it easier to test the project
- Included more code paths into the tests
- Show total test coverage via "make test".
=> Increasing the size of our test coverage

cmd/microservice/server.go, pkg/platform/application/doc.go, pkg/platform/application/service.go, pkg/platform/k8s_repo.go
- Make the platform-api aware of the external host of the cluster for environment variable
=> Expose external url

cmd/microservice/create-service-account.go, pkg/platform/k8s_repo.go
Changes the `create-service-account` command to create a new `devops` rolebinding instead of adding to the existing `developer` rolebinding.
This is so that we don't have to worry about modifying the `developer` rolebinding in the future.
=> Add creation of a new devops rolebinding for the devops svc acc

cmd/microservice/build-terraform-info.go, pkg/platform/doc.go, pkg/platform/storage/git/git_storage.go
Added a few more attributes to the terraformCustomer based on information from the Operations repo.
=> Add more info to the customer struct in terraform.json

cmd/microservice/build-terraform-info.go, cmd/tools/create-customer-hcl.go, pkg/platform/doc.go
- Building the application info to include ModuleName and ApplicationID.
- Terraform create customer now includes the module_name.
=> Adding ModuleName + applicationID

cmd/microservice/server.go, pkg/platform/k8s_repo.go, pkg/platform/microservice/service.go
=> Add restart method and make signatures a little similar

cmd/microservice/server.go, pkg/platform/doc.go, pkg/platform/k8s_repo.go, pkg/platform/microservice/environmentVariables/repo.go, pkg/platform/microservice/environmentVariables/service.go
- api to get the current environment variables in a Studio friendly manner
- api to update environment variables from the Studio
=> Update env variables

pkg/platform/microservice/service.go
- Disable creation of microservice, whilst we fix a few bugs
=> Disabling create + update + delete of microservice

cmd/microservice/server.go, cmd/tools/automate/add-platform-config.go, cmd/tools/automate/get-microservices-metadata.go, cmd/tools/automate/import-dolittle-configmaps.go, cmd/tools/automate/pull-dolittle-config.go, cmd/tools/automate/pull-microservice-deployment.go, cmd/tools/studio/build-application-info.go, cmd/tools/studio/build-studio-info.go, cmd/tools/studio/create-service-account.go, pkg/platform/k8s/setup.go, pkg/platform/k8s_repo.go
Reducing the amount of place we copy the same code to get the client for kubernetes.
Now we can use `k8sClient, k8sConfig := platformK8s.InitKubernetesClient()`
=> Share k8s setup

pkg/platform/k8s_repo.go, pkg/platform/k8s_repo_test.go, pkg/platform/microservice/environmentVariables/repo.go, pkg/platform/microservice/environmentVariables/service.go
Including the environment name in the lookup for microservice name
=> Adding environment to GetMicrosericeName

cmd/microservice/server.go, pkg/platform/application/doc.go, pkg/platform/application/service.go, pkg/platform/doc.go, pkg/platform/storage/studio_info.go
- Reducing the amount of information used for the personalised-info, to that which is currently used in Studio.
- `GetStudioInfo` function to reduce the boiler plate of getting requried info per request.
=> Reduce the information sent via personalised-info api for documentation

cmd/microservice/server.go, cmd/tools/automate/create-application.go, pkg/k8s/dolittle.go, pkg/platform/application/k8s/do_test.go, pkg/platform/application/service_test.go, pkg/platform/microservice/service.go, pkg/platform/microservice/simple/k8s/repo.go
Fixing bug in delete microservice endpoint
=> Make it possible to delete api via api

cmd/tools/studio/build-application-info.go
Rebuilding application state, take status + welcomeMicroservice from storage if exists.
=> Populate status + welcomeMicroservice from storage if exists

.github/workflows/pull-request.yml
- job to build platform-api
- job to build platform-operations
=> Spliting workflow into two jobs

pkg/platform/microservice/handle_simple.go, pkg/platform/microservice/validate.go, pkg/platform/microservice/validate_test.go
Bug creating a microservice, is rejecting if the ingressPath is used in a different environment
=> Bug path check include environment

README.md
Adds CodeClimate badges so that's its easier to navigate to the CodeClimate pages.
=> Add CodeClimate badges for easier access to it and to track status

cmd/tools/terraform/template/application.go, pkg/platform/application/doc.go, pkg/platform/application/k8s.go, pkg/platform/application/service.go
- When creating an application, it is possible to define customTenants per environment
- Creating applications uses ./modules/dolittle-application-with-resources.
=> Create application, environments can have custom ids

cmd/tools/job/template/customer.go, cmd/tools/terraform/template/customer.go
- Remove unused flag
- Fix command description
=> unused flag + wrong text

cmd/api/server.go, pkg/platform/doc.go, pkg/platform/k8s/k8s_repo.go, pkg/platform/microservice/configFiles/repo.go, pkg/platform/microservice/configFiles/service.go, pkg/platform/microservice/environmentVariables/repo.go, pkg/platform/microservice/environmentVariables/service.go
- Config Files support
- Get config files names list for microservice
- Delete config file for microservice
- Add entry to config file configmap for microservice
-  validation
- More descriptive error logging in some of the environment variables repo and service
=> Feature mount files

cmd/api/server.go, pkg/platform/doc.go, pkg/platform/microservice/configFiles/repo.go, pkg/platform/microservice/configFiles/service.go
Resolved remaining comments of [PR 121](https://github.com/dolittle/platform-api/pull/121)
- use logcontext
- log as info for validation messages
- refactoring based on [comments](https://github.com/dolittle/platform-api/pull/121)
=> Pr 121 unresolved fixes

.github/workflows/release-and-deploy.yml
=> Fix typo in deploy jobs

.github/workflows/release-and-deploy.yml
Fix the needs of the deploy workflow and force a deployment
=> Fix the needs of the deploy workflow

.github/workflows/update-configmap-field.yml
Fix environment url check for configmaps
=> Fix environment url check for configmaps

.github/workflows/deploy.yml
Fix deploy typo and force deployment (very good).
=> Fix deploy typo
