dolittle/platform-api

cmd/microservice/root.go, cmd/microservice/server.go
ssh key path was hard coded to one specific dev's machine. I made it configurable so that it's easier for others to run platform  api local.
=> Removed hard coded git ssh key path

cmd/microservice/server.go, pkg/share/logs_service.go
Providing the backups via the same server as the rest.
This is no code change. The biggest change is in Operations.
More work should and will be done to move from json cache, to talking live.
Linked to https://app.asana.com/0/1200403658239260/1200410466873996/f
=> Bring backups to the platform-api

cmd/microservice/git-test.go, pkg/platform/storage/git/application.go, pkg/platform/storage/git/microservice.go, pkg/platform/storage/git/studio.go, pkg/platform/storage/git/tenant.go, pkg/platform/storage/git/terraform.go
Fixes the filepath code to also work with Windows.
- Fixes the code to also understand Windows style path delimiters instead of just *nix paths when reading the repo.
=> Fix dealing with Windows filepaths

cmd/microservice/build-applications.go, pkg/platform/application/service.go, pkg/platform/doc.go
Changes the structure of the HttpInputEnvironment struct so that it knows about the tenants and has a mapping between tenant Id and ingress.
There are some assumptions in play around the ingresses that are added to the map. First it assumes that the ingresses that needs to be configured has one or more spec.TLS items. Secondly it will override the ingress config for a tenant. It also maybe clunkily extracts the tenant id from the ingress from the nginx.ingress.kubernetes.io/configuration-snippet annotation. 
- Changed structure of HttpInputEnvironment to include a list of tenants and a mapping between tenant id and ingress host and domain prefix
- build-applications command to store applications with this new structure
- https://app.asana.com/0/1200879032451150/1200931738686043/f
=> Change git storage applications structure 

pkg/platform/application.go, pkg/platform/application_test.go, pkg/platform/microservice/purchaseorderapi/doc.go, pkg/platform/microservice/purchaseorderapi/handler.go, pkg/platform/microservice/purchaseorderapi/k8sResource.go, pkg/platform/microservice/purchaseorderapi/k8sResourceSpecFactory.go, pkg/platform/microservice/purchaseorderapi/k8sResourceSpecFactory_test.go, pkg/platform/microservice/purchaseorderapi/repo.go, pkg/platform/microservice/rawdatalog/repo.go, pkg/platform/microservice/service.go, pkg/platform/platform_suite_test.go
When creating Purchase Order API microservice or RawDataLogIngestor microservice it is important to configure it to the correct tenant. The tenant being used before was just a static tenant, it needs to not be static in order for it to work with actual customers.
There are a few caveats at the moment:
- It will only use one tenant. For instance if we needed a Purchase Order API to commit events to multiple tenants that wouldn't work with the current solution
- The added configured tenant is not used for the other microservices yet. Only used for Purchase Order API and RawDataLogIngestor
- When we want to do this for normal microservices we need to change this to configure for all tenants, not just the first one 
- A method for getting tenant for environment on the application metadata …
=> Use configured tenant when creating POAPI and RawDataLogIngestor

pkg/platform/storage/git/application.go
When getting applications from git repo start walking the directory from the customer folder, instead of the root of the repo.
- When getting applications from git repo start searching from the customer folder
- Use the logger
=> Filter applications

pkg/platform/microservice/purchaseorderapi/k8sResourceSpecFactory.go, pkg/platform/microservice/purchaseorderapi/k8sResourceSpecFactory_test.go
Fixes the configured HTTP listen on port when deploying a PurchaseOrderAPI microservice, so that it conforms to the convention in the platform (to listen on port 80 for the ingress). Even though we don't have an ingress automatically set up for it now, this makes the pod listen on the port that the service expects it to. So that when we do want to create an ingress (to port 'http') this will work.
I have tested this locally with k3d, and it works.
- Change the created environmental variables for the PurchaseOrderAPI deployment so that it listens on port 80 instead of 8080
=> Change the configured http port for POapi

.github/workflows/check_labels.yml, pkg/platform/microservice/k8s/doc.go, pkg/platform/microservice/purchaseorderapi/doc.go, pkg/platform/microservice/purchaseorderapi/handler.go, pkg/platform/microservice/purchaseorderapi/repo.go, pkg/platform/microservice/purchaseorderapi/repo_test.go
Adds checks to ensure that there doesn't already exist a PurchaseOrderAPI in an environment when creating. The previous logic checked for one with the same name and id, the added code checks for any name and id.
The code might be a bit excessive, as it now first checks the Git storage, and then K8s afterwards. We could get away with one of them, but I'm not sure which one to truly consider the source of truth until we have everything covered by automation. Also might not be clear, but the old check is still useful because it checks for any microservice with the same name (which would cause problems) - even though the naming of the function kind of indicates that it looks for a PurchaseOrderAPI microservice.
I've tested it locally, and also added more specs for the `Exists` method and the …
=> Only allow single PurchaseOrderAPI per environment

pkg/platform/k8s_repo.go
While a pod I starting up, the StartTime is not set (nil in Go) which caused the "View" screen just after creating e.g. a POapi to fail. This fix just returns "N/A" instead of an actual date when StartTime is nil. The contract was just a plain string anyways, so Studio will accept it.
- Start with a clean cluster (or without raw-data-log and purchase-order)
- Click Microservices
- Click Create new microservice
- Click Create within the Purchase order api card
- Select Infor graphic
- Enter name
- Click next
- Enter username
- Enter password
- Click Next
- At this point, we send the request to the backend and redirect the frontend.
- Observe platform-api __does not__ crash
- Handling of Pod.StartTime nil-values while the pod is still starting up.
=> Return "N/A" for start-time when pod is starting up

pkg/platform/microservice/rawdatalog/repo.go, pkg/platform/microservice/rawdatalog/repo_test.go
There was a bug in the raw data log ingestor repo implementation that converted the environment from the microservice from the input to lower case, causing the environment label on the raw data log deployment to be different from the other microservice kind deployments. 
However this fix has a side effect that I don't know the effects of, since we do not convert the environment to lower that results in the DOLITTLE_ENVIRONMENT environment variable on the envVariables config map being different (not lowercased). Is this important? If so we can just make the input there to lower case, that's not a big deal.
EDIT: As of writing this the code in question is on line 444
- Go through test steps in PR in Studio https://github.com/dolittle/Studio/pull/116
- Deployment of raw data log should now …
=> Raw data log microservice bug

pkg/platform/k8s_repo.go
Fixes a minor issue where an array was not initialised to an empty array
- Initialize pods list with empty array
=> Set empty pods

pkg/platform/microservice/service.go
Fixes a bug where if an error occurs during creation of a PurchaseOrderAPI microservice, both the error object and the microservice object was written to the response. Resulting in invalid JSON in the response body.
- Don't append the microservice object to the response body if an error occurs during creation of a PurchaseOrderAPI
=> Don't write microservice object if error occured

cmd/rawdatalog/read-logs.go, pkg/platform/microservice/rawdatalog/repo_test.go, pkg/platform/microservice/rawdatalog/stan.go, pkg/rawdatalog/nats.go
Adds a PersistentVolumeClaim to the STAN deployment with the name of `<env>-stan-storage` for the PVC. It uses the same [`managed-premium`](https://docs.microsoft.com/en-us/azure/aks/concepts-storage#storage-classes) storage class as we use for MongoDB in the platform. The STAN store method is [file](https://docs.nats.io/nats-streaming-server/configuring/persistence/file_store) and the name of the directory is `datastore` like in the STAN doc examples.
To use this locally you have to create a new storage class with the name `managed-premium`, create a persistent volume attached to it, and attach a directory to that persistent volume during k3d creation. This is documented in the Studio PR https://github.com/dolittle/Studio/pull/119
- Adds a PersistentVolumeClaim of 8GB to the STAN …
=> Make STAN deployment persistent

pkg/platform/application/service.go
Querying the /applications data, will now return an empty array, not null.
=> applications in /applications endpoint return empty []

cmd/microservice/create-service-account.go, pkg/platform/k8s_repo.go
Adds the new  `create-service-account` command, which creates a  service account called `devops` and adds it to the `developer` role binding
=> Add create-service-account command

pkg/dolittle/k8s/deployment.go, pkg/platform/microservice/simple_repo.go
Add's the ability to create a base microservice without a Runtime container by defining the wanted Runtime image as `"none"` in the request.
Also adds memory limits to newly created Runtime containers in a microservice. The request is for 250MB and the limit is 1GB.
Related to https://github.com/dolittle/Studio/pull/136
=> Add ability to create a base microservice without a Runtime container

pkg/platform/application/service.go, pkg/platform/doc.go, pkg/platform/k8s_repo.go, pkg/platform/k8s_repo_test.go
- Rename HttpResponseApplications2 to HttpResponseApplication
- Expose the Ingress host + path per customer Tenant ID
- Expose Unique Ingress Paths (microservice paths)
=> Public url for microservices in the platform but not in studio

cmd/tools/automate/import-dolittle-configmaps.go, cmd/tools/automate/root.go
Adds new command `import-dolittle-configmaps`.
Usage:
1. Be in the real cluster context
2. Download all of the dolittle configmaps to `configmaps.json`:
```sh
kubectl get cm -A -l microservice -o json | jq -c '.items[] | select(.metadata.name | test(".+-dolittle$"))' > configmaps.json
```
3. Change context to your local cluster:
```sh
kubectl config use-context k3d-dolittle-dev
```
4. Pipe the `configmaps.json` into the command and see it create all of the namespaces and provided `-dolittle` configmaps:
```sh
cat configmaps.json | go run main.go tools automate import-dolittle-configmaps
```
=> Add  import-dolittle-configmaps

pkg/platform/cicd/service.go
Fixes the `getServiceAccountCredentials()` method to return the whole k8s Secret resource. This is because Azure DevOps requires the whole Secret resource instead of just the data part when setting up a kubernetes connection.
The Studio button that calls this endpoint:
=> Fix getServiceAccountCredentials to return the whole k8s Secret resource

cmd/tools/automate/add-platform-config.go, pkg/platform/automate/share.go, pkg/platform/microservice/businessmomentsadaptor_repo.go, pkg/platform/microservice/purchaseorderapi/doc.go, pkg/platform/microservice/purchaseorderapi/handler.go, pkg/platform/microservice/purchaseorderapi/k8sResource.go, pkg/platform/microservice/purchaseorderapi/repo.go, pkg/platform/microservice/rawdatalog/repo.go, pkg/platform/microservice/service.go, pkg/platform/microservice/simple_repo.go
Changes the `GetDeployment` function to require `applicationID` & `environment` instead of just a `namespace`. This is because some microservices reuse the same microserviceID accross environment. This makes it so that you can reliably always get the correct deployment from the correct environment.
=> Make `GetDeployment` environment aware

Makefile
Fix Makefile server script - Replace 'microservice' with 'api'
Fix Makefile server script - Replace 'microservice' with 'api'
=> Fix Makefile server script

.github/workflows/release.yml
Fix release workflow to only run when a pull request is merged (as per [GitHub example](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-when-a-pull-request-merges), as it used to also run when a pull request was merely closed with unmerged commits. For example PR https://github.com/dolittle/platform-api/pull/100 was closed, but the `release` workflow [still ran for it](https://github.com/dolittle/platform-api/runs/5549733761?check_suite_focus=true). In that case the `dolittle/establish-context-action@v2` action detected that no release should be made (due to [this line](https://github.com/dolittle/establish-context-action/blob/cb95abdb2cb21515db1b45478d6b9da20ca4853f/Source/MergedPullRequestContextEstablisher.ts#L54) and then …
=> Fix release workflow to only run when a pull request is merged

pkg/dolittle/k8s/configmaps.go, pkg/dolittle/k8s/configmaps_test.go, pkg/platform/microservice/simple/k8s/resources.go, pkg/platform/microservice/simple/k8s/resources_test.go
When creating a new microservice that uses the [V8.0.0](https://github.com/dolittle/Runtime/releases/tag/v8.0.0) Runtime, we default to setting the `DOLITTLE__RUNTIME__EVENTSTORE__BACKWARDSCOMPATIBILITY__VERSION` env variable to `V7`. This is set through the `appsettings.json`, where the ASP.NET configuration system will pick it up just like it would be set in the env variable.
We default to `V7`, because to `V6` should only be used when upgrading a V6 Runtime to V8 and we don't currently support upgrading of the Runtime in the platform.
- https://app.asana.com/0/1202023614957161/1202062723906543
- https://github.com/dolittle/Runtime/releases/tag/v8.0.0
- https://github.com/dolittle/Studio/pull/170
=> Add support for V8 Runtime with backwards compatibility set to V7 by default

docs/microservice.md, pkg/platform/doc.go, pkg/platform/microservice/simple/k8s/resources.go, pkg/platform/microservice/simple/k8s/resources_test.go
Adds a new `HttpInputSimpleCommand` struct to the `Extra` field on the request for microservice creation. If the fields aren't specified the `command` and `args` fields will be emitted from the created deployment as the properties have the `omitempty` tag.
- https://github.com/dolittle-platform/Operations/pull/209
- https://app.asana.com/0/1202121266838773/1202159723413336
=> Enable head container commands and args to be defined on microservice creation

cmd/api/server.go, pkg/platform/application/doc.go, pkg/platform/application/service.go, pkg/platform/doc.go, pkg/platform/listeners/doc.go, pkg/platform/listeners/m3connector.go, pkg/platform/listeners/m3connector/kafkafiles.go, pkg/platform/microservice/handle_simple.go, pkg/platform/microservice/service.go, pkg/platform/microservice/simple/k8s/resources.go, pkg/platform/microservice/simple/k8s/resources_test.go, pkg/platform/storage/doc.go, pkg/platform/storage/environment.go
- Listen for changes on where we will write connection details for m3connector and update the application
- Within application a new connection object exists in environment, this is used by the frontend today to provide a simple user experience
- When creating a microservice we will now add the m3connector volumes to the deployment
=> Studio include kafka

pkg/platform/microservice/handle_simple.go
Fix error when trying to create a base microservice without the M3Connector and the environment variable set.
=> Only check if the m3 connector environment variable is set when selecting to use the M3 connector

pkg/platform/microservice/configFiles/configFiles_suite_test.go, pkg/platform/microservice/configFiles/repo.go, pkg/platform/microservice/configFiles/repo_test.go, pkg/platform/microservice/configFiles/service.go
- Fixes a bug with only the `binaryData` property for config files configmaps being used for fetching config files filenames.
- Adds support for both utf8 & non-utf8 files being uploaded as the configs. If the code detects that the incoming config file isn't valid utf8 it's going to get saved to the `binaryData` property. Otherwise it's saved to `data`.
- https://app.asana.com/0/1202121266838773/1202244401000776
=> Add handling for both `data` & `binaryData` properties in configmaps

pkg/platform/microservice/configFiles/repo.go, pkg/platform/microservice/configFiles/repo_test.go
Fixes a bug with config files saved on the configmaps `data` property not being deleted in the `RemoveEntryFromConfigFiles()` method.
- https://app.asana.com/0/1202121266838773/1202261003053932/f
=> Fix `RemoveEntryFromConfigFiles()` method to delete from the data property too

.gitignore, go.mod, go.sum, pkg/dolittle/k8s/deployment.go, pkg/dolittle/k8s/deployment_test.go, pkg/platform/application/k8s/resource_test.go, pkg/platform/application/k8s/resources.go
Hard coding a default resource request and limit for CPU and Memory on:
- Head containers
- Runtime containers
- MongoDB containers (not backup jobs)
The requests are higher for "Prod" environments, according to the suggested default values:
```yaml
environments:
prod:
runtime:
resources:
requests:
cpu: 50m
memory: 256Mi
limits:
cpu: 2000m
memory: 1Gi
head:
resources:
requests:
cpu: 50m
memory: 256Mi
limits:
cpu: 2000m
memory: 1Gi
mongodb:
resources:
requests:
cpu: 100m
memory: 512Mi
limits:
cpu: 2000m
memory: 2Gi
non-prod:
runtime:
resources:
requests:
cpu: 25m
memory: 256Mi
limits:
cpu: 2000m
memory: 1Gi
head:
resources:
requests:
cpu: 25m
memory: 256Mi
limits:
cpu: 2000m
memory: 1Gi
mongodb:
resources:
requests:
cpu: 50m
memory: 512Mi
limits:
cpu: 2000m
memory: 2Gi
```
=> Adding resource limits for head

.github/workflows/deploy.yml, .github/workflows/release-and-deploy.yml
Simplify the deployment workflow so that it doesn't require 2 rounds of approvals. Due to the limitations of reusable workflows in GitHub we sadly can't use the other 2 reusable workflows to do this. Also forces a deployment.
=> Add new deploy workflow to consolidate the steps

cmd/tools/job/rerun.go, cmd/tools/job/root.go
Adds new `tools job rerun` command that allows us to easily rerun failed jobs.
Example usage:
```sh
go run main.go tools job rerun joeltest                    
{"command":"rerun","job_name":"joeltest","level":"info","msg":"attempting to rerun the job","time":"2022-08-02T14:54:25+02:00"}
{"command":"rerun","job_name":"joeltest","level":"info","msg":"deleting the job","time":"2022-08-02T14:54:25+02:00"}
{"command":"rerun","job_name":"joeltest","level":"info","msg":"The job was deleted, recreating it","time":"2022-08-02T14:54:25+02:00"}
{"command":"rerun","job_name":"joeltest","level":"info","msg":"done","time":"2022-08-02T14:54:25+02:00"}
```
- https://app.asana.com/0/1202121266838773/1202697181786464
=> Add new `tools job rerun` command to rerun failed jobs
